export const scheduleScopeName = 'scheduleScopeName'
export const ruleId = 'ruleId'
export const setName = 'setName'
export const relationshipCode = 'relationshipCode'
export const carSeries = 'carSeriesCode'
export const opposite = 'opposite'