export const active = 'active'
export const carSeriesCode = 'carSeriesCode'
export const carSeriesMapColour = 'carSeriesMapColour'
export const lineMapId = 'lineMapId'
export const seriesMapGroupId = 'seriesMapGroupId'
export const seriesMapName = 'seriesMapName'
