export const attributeValue = 'attributeValue'
export const attributeName = 'attributeName'
export const carSeries = 'carSeriesCode'
export const featureCode = 'featureCode'
export const scheduleScopeName = 'scheduleScopeName'
