export const scheduleScopeName = 'scheduleScopeName'
export const scheduleStartPeriod = 'scheduleStartPeriod'
export const scheduleEndPeriod = 'scheduleEndPeriod'
export const previousSolutionName = 'previousSolutionName'
export const previousScheduleScopeName = 'previousScheduleScopeName'
export const offlineStartShift = 'offlineStartShift'
export const offlineEndShift = 'offlineEndShift'
export const lineMapId = 'lineMapId'
