export const id = 'id'
export const lineId = 'lineId'
export const upperLimit = 'upperLimit'
export const lowerLimit = 'lowerLimit'
export const active = 'active'
export const keyZoneCode = 'keyZoneCode'
export const seriesMapPatternName = 'seriesMapPatternName'
export const extendedLeadTimeGap = 'extendedLeadTimeGap'
